'use client';

import React, { useState } from 'react';
import { 
  Compass, 
  Sparkles, 
  ShieldCheck, 
  Coins, 
  Flame, 
  Layers, 
  ExternalLink, 
  CheckCircle2, 
  ArrowRight,
  TrendingUp,
  History,
  Clock,
  Database,
  Cpu
} from 'lucide-react';
import { Language } from '@/lib/brew-data/types';

interface BrewHistoryTimelineProps {
  lang: Language;
}

interface MilestoneItem {
  id: string;
  epoch: string;
  year: string;
  dateStr: string;
  titleEn: string;
  category: 'genesis' | 'security' | 'bstocks' | 'factory' | 'deflation' | 'indexer';
  badgeText: string;
  summaryEn: string;
  detailsEn: string[];
  blockHeight?: string;
  contract?: string;
  metric?: { labelEn: string; value: string };
  illustrationUrl?: string;
}

export default function BrewHistoryTimeline({ lang: _lang }: BrewHistoryTimelineProps) {
  const [selectedEpoch, setSelectedEpoch] = useState<string>('all');
  const [expandedId, setExpandedId] = useState<string | null>('genesis-launchpad');

  const milestones: MilestoneItem[] = [
    {
      id: 'genesis-launchpad',
      epoch: 'Epoch I',
      year: '2024 Q1',
      dateStr: 'January 2024',
      titleEn: 'Genesis of Brew & The Anti-Rugpull Covenant',
      category: 'genesis',
      badgeText: 'Genesis',
      summaryEn: 'Initial protocol launch on BNB Smart Chain engineered to eradicate predatory liquidity rugpulls, honeypots, and manipulative presales.',
      detailsEn: [
        'Confronting widespread creator liquidity drain scams across the BNB Smart Chain ecosystem in late 2023, the brew.family founders banded together to build a fair-launch platform where liquidity theft is mathematically eliminated.',
        'Initial token liquidity was mandatorily channeled into PancakeSwap V3 and permanently locked inside smart contracts with zero principal extraction methods.',
        'Tokens launch with a fixed 1,000,000,000 supply, zero mint functions, zero hidden taxes, and no privileged developer owner keys.'
      ],
      blockHeight: 'Block ~35,120,000+',
      contract: '0xeEa6C3bfb29Fd9a35380438956bae7B109c63d85',
      metric: { labelEn: 'Liquidity Guarantee', value: '100% Irrevocably Locked' },
      illustrationUrl: '/illustrations/founders-chronicles.jpg'
    },
    {
      id: 'liquidity-locker-custody',
      epoch: 'Epoch II',
      year: '2024 Q2',
      dateStr: 'April 2024',
      titleEn: 'Formal Verification of BrewLiquidityLocker on BSC',
      category: 'security',
      badgeText: 'Security',
      summaryEn: 'Deployment of the NFT liquidity custody contract eliminating all principal withdrawal functions, even for protocol administrators.',
      detailsEn: [
        'BrewLiquidityLocker was deployed to BSC Mainnet and 100% verified on BscScan.',
        'Operating as an absolute cryptographic vault: PancakeSwap V3 LP NFT positions are locked indefinitely, exposing only trading fee collection routines to valid recipients.',
        'Trading fees generated by the concentrated liquidity pool are systematically separated: launched token fees are incinerated forever, while paired quote fees are distributed.'
      ],
      blockHeight: 'Block ~37,840,000+',
      contract: '0x3366e32702d6116B4FD2Cd3353dE2D5fF993F0d4',
      metric: { labelEn: 'Access Audit', value: 'Zero Backdoors' },
      illustrationUrl: '/illustrations/law-disclaimer.jpg'
    },
    {
      id: 'bstocks-integration',
      epoch: 'Epoch III',
      year: '2024 Q3',
      dateStr: 'August 2024',
      titleEn: 'The bStocks Revolution: Tokenized Global Equities',
      category: 'bstocks',
      badgeText: 'Innovation',
      summaryEn: 'Brew pioneered direct trading pairs against global equities: Tesla, Apple, SpaceX, NVIDIA, GameStop, and the S&P 500 ETF.',
      detailsEn: [
        'Through the bStocks ecosystem partnership on BNB Chain, token creators gained the unprecedented ability to pair community tokens directly against real-world equities.',
        'Expands launch options beyond standard WBNB, allowing direct trading against global tech titans like Tesla (TSLAb), NVIDIA (NVDAb), Apple (AAPLAb), and SpaceX (SPACEXb).',
        'Bridged traditional Wall Street equities and decentralized community memecoins into a unified, frictionless AMM marketplace.'
      ],
      blockHeight: 'Block ~41,200,000+',
      metric: { labelEn: 'Tokenized Equities', value: '11+ Global Equities' },
      illustrationUrl: '/illustrations/bstocks-bourse.jpg'
    },
    {
      id: 'multipair-factories',
      epoch: 'Epoch IV',
      year: '2024 Q4',
      dateStr: 'November 2024',
      titleEn: 'Factory Evolution: MultiPair Factory V1 & V2',
      category: 'factory',
      badgeText: 'Scalability',
      summaryEn: 'Architectural progression from single-pair pools to simultaneous atomic multi-pool launches supporting up to 5 asset pairs per token.',
      detailsEn: [
        'Deployment of BrewMultiPairFactoryV1 and subsequent refinement in MultiPair Factory V2.',
        'Empowered creators to launch a single token with dual or multi-liquidity pools (e.g., WBNB + USDT or WBNB + Tesla bStock) in a single atomic transaction.',
        'Included multi-transaction execution queues to prevent gas limit failures when provisioning deep liquidity across multiple ticks.'
      ],
      blockHeight: 'Block ~44,150,000+',
      contract: '0x21653fa9c9562d55a162c17D2eF33Fc0FaB7Ea71',
      metric: { labelEn: 'Pairing Capacity', value: 'Up to 5 Pools' },
      illustrationUrl: '/illustrations/architecture-map.jpg'
    },
    {
      id: 'buyback-distributor',
      epoch: 'Epoch V',
      year: '2025 Q1',
      dateStr: 'January 2025',
      titleEn: 'BrewDistributorFactory: The Autonomous Buyback Engine',
      category: 'deflation',
      badgeText: 'Deflation',
      summaryEn: 'Introduced permissionless community buyback & burn contracts routing creator trading fees to autonomous market purchases.',
      detailsEn: [
        'Deployment of BrewDistributorFactory (0xd765972dD6a09Fa9c743b4708198A820FC5D31EE) on BNB Smart Chain.',
        'Allowed creators to permanently renounce their 50% paired-token fees into an automated buyback machine that purchases the token on PancakeSwap V3 and transfers it to 0x...dead.',
        'Anyone can trigger the distributor permissionlessly once rewards accumulate, creating relentless buying pressure and deflation.'
      ],
      blockHeight: 'Block ~48,920,000+',
      contract: '0xd765972dD6a09Fa9c743b4708198A820FC5D31EE',
      metric: { labelEn: 'Token Burn Rate', value: '100% of Token Fees' },
      illustrationUrl: '/illustrations/buyback-phoenix.jpg'
    },
    {
      id: 'checkpoint-oracle-1050',
      epoch: 'Epoch VI',
      year: '2025 - 2026',
      dateStr: 'Contemporary Era',
      titleEn: '1,050+ On-Chain Launches & The Checkpoint Oracle',
      category: 'indexer',
      badgeText: 'Milestone',
      summaryEn: 'Brew crossed over 1,050 verified launches on BSC, synchronized across 5 factory sources with real-time GeckoTerminal and DEX Screener indexing.',
      detailsEn: [
        'The protocol checkpoint infrastructure (`launch-checkpoints.json`) tracks 1,050+ on-chain launches across BSC block heights reaching 120,489,295+.',
        'Factory sources include Single-Pair (1,017 tokens), MultiPair V1 (26 tokens), MultiPair V2 (5 tokens), and specialized deployers.',
        'A full 80% of claimed protocol fees are systematically channeled into open-market $BREW buybacks, while 100% of token-side swap fees burn perpetually.'
      ],
      blockHeight: 'Block ~120,489,295+',
      contract: '0x0F8708A91D8e3B3458BE94d32caa6e62e98DaEdc',
      metric: { labelEn: 'Verified Launches', value: '1,050+ BSC Tokens' },
      illustrationUrl: '/illustrations/checkpoint-oracle.jpg'
    }
  ];

  const filtered = selectedEpoch === 'all' 
    ? milestones 
    : milestones.filter(m => m.category === selectedEpoch);

  return (
    <div className="space-y-4 font-sans text-xs text-[#2e2319]">
      {/* Header */}
      <div className="border-b border-[#cfbe9f] pb-3">
        <div className="flex items-center justify-between">
          <span className="text-[10px] font-bold uppercase tracking-wider text-[#8b5928] flex items-center gap-1">
            <History className="w-3.5 h-3.5" />
            <span>CHRONICLES & PROTOCOL HISTORY</span>
          </span>
          <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-[#ebdcc1] text-[#69431d] font-semibold">
            BSC On-Chain Snapshot · Block 120M+
          </span>
        </div>
        <h2 className="text-xl font-bold font-serif text-[#392618] mt-0.5">
          The Historical Timeline of Brew Protocol
        </h2>
        <p className="text-[11px] text-[#6b5842]">
          The verifiable chronological journey of smart contract innovations, bStocks equity bridging, and deflationary economics on BNB Chain.
        </p>
      </div>

      {/* Epoch Filter Pills */}
      <div className="flex flex-wrap gap-1.5 pt-1">
        {[
          { id: 'all', label: 'All Eras' },
          { id: 'genesis', label: 'Genesis & Mission' },
          { id: 'security', label: 'Locker Security' },
          { id: 'bstocks', label: 'bStocks Equities' },
          { id: 'factory', label: 'Factory Evolution' },
          { id: 'deflation', label: 'Buyback & Burn' },
          { id: 'indexer', label: '1,050+ Checkpoint Index' },
        ].map((f) => (
          <button
            key={f.id}
            onClick={() => setSelectedEpoch(f.id)}
            className={`px-2.5 py-1 rounded text-[11px] font-medium transition-colors cursor-pointer ${
              selectedEpoch === f.id
                ? 'bg-[#4a301e] text-[#fbf6ea] shadow-xs'
                : 'bg-[#eee4cf] text-[#5e4a36] hover:bg-[#e4d7bf]'
            }`}
          >
            {f.label}
          </button>
        ))}
      </div>

      {/* Timeline Stream */}
      <div className="space-y-3 max-h-[500px] overflow-y-auto pr-1">
        {filtered.map((item, idx) => {
          const isExpanded = expandedId === item.id;
          return (
            <div
              key={item.id}
              className={`p-3.5 rounded-lg border transition-all ${
                isExpanded 
                  ? 'bg-[#fcf9f2] border-[#a88657] shadow-sm' 
                  : 'bg-[#fdfcf9] border-[#dfd4c0] hover:border-[#bda177]'
              }`}
            >
              {/* Top row */}
              <div 
                onClick={() => setExpandedId(isExpanded ? null : item.id)}
                className="flex items-start justify-between gap-2 cursor-pointer select-none"
              >
                <div className="flex items-start gap-2.5">
                  <div className="w-7 h-7 rounded-full bg-[#ebdcc1] text-[#69431d] font-bold text-xs flex items-center justify-center shrink-0 border border-[#bfa886]">
                    {idx + 1}
                  </div>
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="text-[10px] uppercase font-bold text-[#8f5d2b] tracking-wider">
                        {item.epoch} · {item.year}
                      </span>
                      <span className="text-[9px] px-1.5 py-0.2 rounded font-semibold bg-[#e8c880]/40 text-[#694420]">
                        {item.badgeText}
                      </span>
                    </div>
                    <h3 className="font-serif font-bold text-[#352517] text-sm mt-0.5">
                      {item.titleEn}
                    </h3>
                  </div>
                </div>

                <div className="flex items-center gap-2 shrink-0">
                  <span className="text-[10px] font-mono text-[#8a7259] hidden sm:inline">
                    {item.dateStr}
                  </span>
                  <div className="p-1 rounded bg-[#eee5d3] text-[#71593f]">
                    <ArrowRight className={`w-3.5 h-3.5 transition-transform ${isExpanded ? 'rotate-90' : ''}`} />
                  </div>
                </div>
              </div>

              {/* Summary */}
              <p className="text-[11px] text-[#5e4b37] mt-2 font-serif italic pl-9">
                &ldquo;{item.summaryEn}&rdquo;
              </p>

              {/* Expanded details */}
              {isExpanded && (
                <div className="mt-3 pt-3 border-t border-[#e8ddc8] pl-9 space-y-3">
                  {/* Embedded Historical Engraving */}
                  {item.illustrationUrl && (
                    <div className="my-2 p-1.5 bg-[#f4ece0] border border-[#cfbe9f] rounded-lg">
                      <div className="image-container relative w-full h-40 sm:h-48 overflow-hidden rounded border border-[#bfa987] bg-black/5 flex items-center justify-center">
                        {/* eslint-disable-next-line @next/next/no-img-element */}
                        <img
                          src={item.illustrationUrl}
                          alt={item.titleEn}
                          className="w-full h-full object-contain sepia-[0.12] contrast-[1.05]"
                        />
                      </div>
                      <p className="text-[10px] italic text-[#6e5842] text-center mt-1">
                        Historical plate for {item.titleEn}
                      </p>
                    </div>
                  )}

                  <div className="space-y-1.5">
                    {item.detailsEn.map((detail, dIdx) => (
                      <div key={dIdx} className="flex items-start gap-2 text-[11px] text-[#443324] leading-relaxed">
                        <CheckCircle2 className="w-3.5 h-3.5 text-[#8f5e2d] shrink-0 mt-0.5" />
                        <span>{detail}</span>
                      </div>
                    ))}
                  </div>

                  {/* Metadata Chips */}
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-2 pt-1 font-mono text-[10px]">
                    {item.blockHeight && (
                      <div className="p-2 bg-[#f4ece0] rounded border border-[#dfd4c0] flex items-center justify-between">
                        <span className="text-[#846f5b]">Block Height</span>
                        <span className="font-bold text-[#352517]">{item.blockHeight}</span>
                      </div>
                    )}
                    {item.contract && (
                      <div className="p-2 bg-[#f4ece0] rounded border border-[#dfd4c0] flex items-center justify-between">
                        <span className="text-[#846f5b]">Contract</span>
                        <a
                          href={`https://bscscan.com/address/${item.contract}`}
                          target="_blank"
                          rel="noreferrer"
                          className="font-bold text-[#8d5b27] hover:underline flex items-center gap-1"
                        >
                          <span>{item.contract.slice(0, 6)}...{item.contract.slice(-4)}</span>
                          <ExternalLink className="w-2.5 h-2.5" />
                        </a>
                      </div>
                    )}
                    {item.metric && (
                      <div className="p-2 bg-[#e8dbc2] rounded border border-[#cebfa2] flex items-center justify-between">
                        <span className="text-[#694827]">{item.metric.labelEn}</span>
                        <span className="font-bold text-[#2e1d0f]">{item.metric.value}</span>
                      </div>
                    )}
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
